class AppStrings {
  static const logIn = "Login";
  static const taxonomy = "Taxonomy";
  static const year = "Year";
  static const category = "Category";
  static const logout = "Logout";
  static const signInToYourAccount = "Sign in to your account";
  static const areYouSureYouWantToLogout = "are You Sure You Want To Logout";
  static const createYourAccount = "Create your account";
  static const company = "Company";
  static const cancel = "Cancel";
  static const name = "Name";
  static const email = "Email";
  static const dontHaveAnAccount = "Don't have an account?";
  static const password = "Password";
  static const confirmPassword = "Confirm Password";
  static const confirm = "Confirm";
  static const alreadyHaveAccount = "Already have an account?";
  static const signUp = "Sign Up";
  static const signIn = "Sign in";
  static const rememberMe = "RememberMe";
  static const fullName = "Full Name";
  static const country = "Country";
  static const imInterested = "I'm interested in:";
  static const harvestReports = "Harvest Reports";
  static const price = "Price";
  static const pricess = "PRICES";
  static const agriConversionCalculator = "Agri Conversion Calculator";
  static const favoritePrice = "Favorite Price";
  static const favoritePrices = "FAVORITE PRICE";
  static const addToWatchlist = "ADD TO WATCHLIST";
  static const bushelsMetricTons = "Bushels = Metric Tons";
  static const inputAndConvertValues = "Input And Convert Values Between Bushels And Metric Tons.";
  static const bushels = "BUSHELS: (bu)";
  static const equals = "equals....";
  static const noData = "No data ....";
  static const metricTons = "METRIC TONS: (MT)";
  static const calculationBu = "Calculation:\n1 bu = 0.0272 MT";
  static const bu = "1 bu = 0.0272 MT";
  static const clear = "Clear";
  static const wheatLetter = "Wheat Letter";
  static const subscribe = "Subscribe";
  static const watchlist = "Watchlist";
  static const quality = "Quality";
  static const reports = "Reports";
  static const reportsTypes = "Reports Types";
  static const read = "Read";
  static const view = "View";
  static const region = "REGION";
  static const wheatData = "WHEAT DATA";
  static const currentAverage = "Current Average";
  static const finalAverage = "2024 Final Average";
  static const yearAverage = "5-Year Average";
  static const lbBu = "TW (lb/bu)";
  static const kgHl = "TW (kg/hl)";
  static const distanceArea = "DISTANCE & AREA";
  static const hardRedWinter = "HARD RED WINTER";
  static const hardRedSpring = "HARD RED SPRING ";
  static const softRedWinter = "SOFT RED WINTER";
  static const softWhite = "SOFT WHITE";
  static const northernDurum = "NORTHERN DURUM";
  static const nearby = "NEARBYS:";
  static const weekChange = "WEEK CHANGE:";
  static const oneYearAgo = "ONE YEAR AGO:";
  static const lastPrDate = "LAST PR DATE:";
  static const fwdPrice = "FWD PRICE";
  static const account = "ACCOUNT";
  static const pages = "PAGES";
  static const classs = "CLASS";
  static const testWtkghl = "testWtkghl";
  static const testWtbbu = "testWtbbu";
  static const moisture = "Moisture";
  static const prot12 = "Prot12%mb";
  static const dryBasisProt = "DryBasisProt";
  static const date = "DATE";
  static const data = "Wheat Data";
  static const news = "News";
  static const settings = "SETTINGS";
  static const search = "Search";
  static const gulfOfMexico = "Gulf of Mexico";
  static const calculator = "Calculator";
  static const noDataFound = "No data found";
  static const wheatAssociates = "U.S. Wheat Associates";
  static const error500 = "We are working on server, Please try again later.";
  static const error503 = "Server is under maintenance, Please try again later.";
  static const subscriberConsent = "Subscriber consent";
  static const iConsentToReceivingEmail = "I consent to receiving email communications. ";
  static const iConsentToHavingMySubscriber = "I consent to having my subscriber engagement tracked and analyzed.";
  static const milesKilometer = "MILES = KILOMETERS";
  static const squareFeetSquareMeters = "SQUARE FEET = SQUARE METERS";
  static const metersYardsFeet = "METERS = YARDS = FEET";
  static const acresHectaresMu = "ACRES = HECTARES = MU";
  static const weight = "WEIGHT";
  static const bushelsMetric = "BUSHELS = METRIC TONS";
  static const metricTonToKgPound = "METRIC TONS = KILOGRAMS = POUNDS";
  static const metricTonsCwt = "METRIC TONS = CWT";
  static const yield = "YIELD";
  static const buAcreMtHectare = "BUSHELS ACRE = METRIC TONS HECTARE";
  static const protein = "PROTEIN";
  static const temperature = "TEMPERATURE";
  static const fahrenheitCelsius =  "FEHRENHEIT = CELSIUS";

}
