class AppStrings {
  static const logIn = "Login";
  static const delete = "Delete";
  static const done = "Done";
  static const deleteUser = "Delete User";
  static const noWatchlistAdded = "No Watchlist Added";
  static const uSWheatNewsFeed = "US Wheat News Feed";
  static const yesDeleteMyAccount = "Yes, delete my account";
  static const onceYouDeleteYourAccountThereIsNoWayBackMakeSureYouWantToDoThis =
      "Once you delete your account, there is no getting it back. Make sure you want to do this.";
  static const accountDeletion = "Account Deletion";
  static const taxonomy = "Taxonomy";
  static const year = "Year";
  static const noDataAvailable = "No Data Available";
  static const month = "Month";
  static const day = "Day";
  static const next = "Next";
  static const back = "Back";
  static const ye = "YEAR";
  static const category = "Category";
  static const newPassword = "New Password";
  static const passwordChangedSuccessfully = "Password changed successfully";
  static const newPasswordHint =
      "Your new password must be different from previous used passwords";
  static const bothPasswordsMustMatch = "Both passwords must match";
  static const logout = "Logout";
  static const signInToYourAccount = "Sign in to your account";
  static const createNewPassword = "Create New Password";
  static const areYouSureYouWantToLogout = "are You Sure You Want To Logout";
  static const type = "Type";
  static const createYourAccount = "Create your account";
  static const company = "Company";
  static const cancel = "Cancel";
  static const name = "Name";
  static const email = "Email";
  static const dontHaveAnAccount = "Don't have an account?";
  static const forgotPassword = "Forgot Password ??";
  static const password = "Password";
  static const confirmPassword = "Confirm Password";
  static const confirm = "Confirm";
  static const alreadyHaveAccount = "Already have an account?";
  static const signUp = "Sign Up";
  static const signIn = "Sign in";
  static const resetPassword = "Reset Password";
  static const rememberMe = "RememberMe";
  static const fullName = "Full Name";
  static const country = "Country";
  static const imInterested = "I'm interested in:";
  static const harvestReports = "Harvest Reports";
  static const price = "Prices";
  static const pricess = "PRICES";
  static const agriConversionCalculator = "Agri Conversion Calculator";
  static const favoritePrice = "Favorite Price";
  static const favoritePrices = "FAVORITE PRICE";
  static const addToWatchlist = "ADD TO WATCHLIST";
  static const bushelsMetricTons = "Bushels = Metric Tons";
  static const inputAndConvertValues =
      "Input And Convert Values Between Bushels And Metric Tons.";
  static const bushels = "BUSHELS: (bu)";
  static const equals = "equals....";
  static const noData = "No data ....";
  static const metricTons = "METRIC TONS: (MT)";
  static const calculationBu = "Calculation:\n1 bu = 0.0272 MT";
  static const bu = "1 bu = 0.0272 MT";
  static const clear = "Clear";
  static const wheatLetter = "Wheat Letter";
  static const subscribe = "Subscribe";
  static const watchlist = "Watchlist";
  static const quality = "Quality";
  static const qua = "QUALITY";
  static const reports = "Reports";
  static const reportsTypes = "Reports Types";
  static const read = "Read";
  static const view = "View";
  static const region = "Region";
  static const select = "Select";
  static const wheatData = "WHEAT DATA";
  static const currentAverage = "Current Avg";
  static const finalAverage = "Final Avg";
  static const fiveYearAverage = "5-Year Avg";
  static const lbBu = "TW (lb/bu)";
  static const kgHl = "TW (kg/hl)";
  static const distanceArea = "DISTANCE & AREA";
  static const testWeight = "TEST WEIGHT";
  static const hardRedWinter = "HARD RED WINTER";
  static const hardRedSpring = "HARD RED SPRING ";
  static const softRedWinter = "SOFT RED WINTER";
  static const softWhite = "SOFT WHITE";
  static const northernDurum = "NORTHERN DURUM";
  static const nearby = "NEARBYS:";
  static const weekChange = "WEEK CHANGE:";
  static const oneYearAgo = "ONE YEAR AGO:";
  static const lastPrDate = "LAST PR DATE:";
  static const fwdPrice = "FWD PRICE";
  static const account = "ACCOUNT";
  static const pages = "PAGES";
  static const classs = "Class";
  static const testWtkghl = "TW kg/hl";
  static const testWtbbu = "TW lb/bu";
  static const moisture = "Moisture";
  static const moist = "Moist";
  static const prot12 = "Pro-12%";
  static const proteinMb = "Protein 12% mb";
  static const dryBasisProt = "DryBasisProt";
  static const proteinDryBasis = "Protein dry basis";
  static const proDb = "Pro-db";
  static const date = "Date";
  static const data = "Data";
  static const news = "News";
  static const settings = "SETTINGS";
  static const search = "Search";
  static const gulfOfMexico = "Gulf of Mexico";
  static const calculator = "Calculator";
  static const newFeed = "News Feed";
  static const changePassword = "Change Password ";
  static const noDataFound = "No data found";
  static const wheatAssociates = "U.S. Wheat Associates";
  static const error500 = "We are working on server, Please try again later.";
  static const error503 =
      "Server is under maintenance, Please try again later.";
  static const subscriberConsent = "Subscriber consent";
  static const iConsentToReceivingEmail =
      "I consent to receiving email communications. ";
  static const iConsentToHavingMySubscriber =
      "I consent to having my subscriber engagement tracked and analyzed.";
  static const milesKilometer = "MILES = KILOMETERS";
  static const squareFeetSquareMeters = "SQUARE FEET = SQUARE METERS";
  static const metersYardsFeet = "METERS = YARDS = FEET";
  static const acresHectares = "ACRES = HECTARES ";
  static const weight = "WEIGHT";
  static const bushelsMetric = "BUSHELS = METRIC TONS";
  static const metricTonToKgPound = "METRIC TONS = KILOGRAMS = POUNDS";
  static const metricTonsCwt = "METRIC TONS = CWT";
  static const commonWheat = "COMMON WHEAT";
  static const yield = "YIELD";
  static const buAcreMtHectare = "BUSHELS/ACRE  =  MT/HECTARE";
  static const protein = "PROTEIN";
  static const flourProtein = "FLOUR PROTEIN";
  static const temperature = "TEMPERATURE";
  static const removedFromWatchlist = "Removed from watchlist";
  static const failedToRemove = "Failed to remove";
  static const fahrenheitCelsius = "FAHRENHEIT = CELSIUS";
  static const alreadyAddedToWatchlist =
      "This date is already in your watchlist.";
  static const watchlistAddedSuccessfully = "Watchlist Added Successfully";
  static const pleaseSelectDateBeforeAddingToWatchlist =
      "Please select a date before adding to watchlist";

  static const syncNewData = "Sync New Data";
  static const dataNotAvailable = "Data Not Available";
}
